### ISSUE TITLE
Suggest parentheses around && within ||

### ISSUE THREAD

**Issue by m1rakuru** [matthiaskramm/gfxpoly#2]
In poly.c:
287: if(a.x == p2->x && a.y == p2->y ||
b.x == p2->x && b.y == p2->y) {
1098:
if(!(d0>=0 && d1>=0 && d2>=0 && d3>0 ||
d0<=0 && d1<=0 && d2<=0 && d3<0)) {

**Comment by matthiaskramm** [comment]
I've never fully understood the need for extra parentheses when && are || involved. Do some C/C++ compilers have bugs in their boolean operator precedence?

Or is this a compiler warning? If so, what compiler are you using?

**Comment by m1rakuru** [comment]
I am using gcc. This is really a compiler warning.

**Comment by matthiaskramm** [comment]
Should be fixed now.
