### ISSUE TITLE
Many unused variables

### ISSUE THREAD

**Issue by m1rakuru** [matthiaskramm/gfxpoly#3]
For example:
poly.c: In function 'gfxpoly_size':
poly.c:214:11: warning: unused variable 't' [-Wunused-variable]
     int s,t;
           ^
poly.c:214:9: warning: unused variable 's' [-Wunused-variable]
     int s,t;
         ^
poly.c: In function 'gfxpoly_check':
poly.c:227:11: warning: unused variable 't' [-Wunused-variable]
     int s,t;

and another set of variables...
gcc compiler.

**Comment by matthiaskramm** [comment]
Fixed. There really were a lot of these.
